### PR TITLE
app_rpt: Don't crash without access to parallel port

### LINKED ISSUE #653: Enabling Parallel Port Causes Crash - Asterisk not in LP Group
Enabling the parallel port for I/O on a Debian installation causes `asterisk.service` to crash and coredump upon restart due to the `asterisk` user not being part of the `lp` group to access the hardware.

Steps to reproduce:

- add `iobase = 0x0378` to `rpt.conf`
- add `pp3 = ptt` to `simpleusb.conf`
- restart asterisk with `sudo systemctl restart asterisk`

Get:

```
ve7fet@asl3:/etc/asterisk$ sudo systemctl restart asterisk
Job for asterisk.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status asterisk.service" and "journalctl -xeu asterisk.service" for details.
```

```
ve7fet@asl3:/etc/asterisk$ sudo tail /var/log/asterisk/messages.log
[2025-04-24 10:46:46.688] ERROR[8391] res_usbradio.c: Can't get io permission on IO port 0378 hex, disabling pp support
```

So, it knows it can't get permissions for the parallel port and disables support, but fails in spectacular fashion to handle it gracefully, and just crashes.

Adding `asterisk` to the `lp` group resolves the issue:

`sudo adduser asterisk lp`

```
ve7fet@asl3:/etc/asterisk$ sudo adduser asterisk lp
Adding user `asterisk' to group `lp' ...
Done.
ve7fet@asl3:/etc/asterisk$ sudo systemctl restart asterisk
ve7fet@asl3:/etc/asterisk$ sudo tail /var/log/asterisk/messages.log
[2025-04-24 10:51:03.983] NOTICE[10081] chan_dahdi.c: Ignoring any changes to 'vmsecret' (on reload) at line 36.
[2025-04-24 10:51:03.983] NOTICE[10081] chan_dahdi.c: Ignoring any changes to 'hasiax' (on reload) at line 40.
[2025-04-24 10:51:03.983] NOTICE[10081] chan_dahdi.c: Ignoring any changes to 'hasmanager' (on reload) at line 48.
[2025-04-24 10:51:03.983] WARNING[10081] chan_dahdi.c: Only FXO signalled channels may belong to a call group
[2025-04-24 10:51:03.983] WARNING[10081] chan_dahdi.c: Only FXO signalled channels may belong to a pickup group
[2025-04-24 10:51:04.402] WARNING[10086] pbx_config.c: users.conf is deprecated and will be removed in a future version of Asterisk
[2025-04-24 10:51:04.516] NOTICE[10124] app_rpt.c: Normal Repeater Init  1999
[2025-04-24 10:51:04.520] NOTICE[10127] chan_simpleusb.c: Channel 1999: Set option TONE VERIFY, mode: OFF(0).
[2025-04-24 10:51:04.817] WARNING[10127] chan_simpleusb.c: Possibly stuck USB read channel. [1999]
[2025-04-24 10:51:04.850] WARNING[10127] chan_simpleusb.c: USB read channel [1999] was not stuck.
```

### LINKED ISSUE #654: Cop 61/62 Silently Fail When CAPS Not Used
The Cop commands 61/62 can be used for controlling GPIO/Parallel Port I/O pins.

```
rpt cmd 1999 cop 61,PP2=0 0; turn physical Pin 2 off
rpt cmd 1999 cop 61,PP2=1 0; turn physical Pin 2 on
```

Controlling GPIO is similar.

If you don't capitalize the "PPx" or "GPIOx", nothing happens, there is no error/feedback, the command just silently fails (an you scratch your head as to why the pin didn't toggle).

Pretty much every other setting defaults to lower case being the generally acceptable syntax.

Perhaps we can either change the code to accept lower case, be case insensitive, or throw an error/warning if the syntax isn't correct?

### PR DESCRIPTION
**Pull request by mkmer**
Don't crash without access to parallel port.
Allow PP= , pp= , pP=,  or Pp= for parallel port strings.
Allow all cases for GPIO= as well  
Fixes #653
Fixes #654

### CODE REVIEW

File: apps/app_rpt/rpt_functions.c [hunk 1]
```diff
@@ -1686,7 +1686,7 @@ int function_cop(struct rpt *myrpt, char *param, char *digitbuf, int command_sou
 			if (sscanf(argv[i], "GPIO" N_FMT(d) "=" N_FMT(d), &j, &k) == 2 || sscanf(argv[i], "GPIO" N_FMT(d) ":" N_FMT(d), &j, &k) == 2) {
 				sprintf(string, "GPIO %d %d", j, k);
 				ast_sendtext(myrpt->rxchannel, string);
-			} else if (sscanf(argv[i], "PP" N_FMT(d) "=" N_FMT(d), &j, &k) == 2) {
+			} else if ((sscanf(argv[i], "PP" N_FMT(d) "=" N_FMT(d), &j, &k) == 2) || (sscanf(argv[i], "pp" N_FMT(d) "=" N_FMT(d), &j, &k) == 2) {
```
Comment (Allan-N) [inline apps/app_rpt/rpt_functions.c:1689]: You may (or may not) like this :
```
			} else if ((sscanf(argv[i], "%*2[pP]" N_FMT(d) "=" N_FMT(d), &j, &k) == 2) {
```

Comment (mkmer) [reply apps/app_rpt/rpt_functions.c:1689]: Funny, I thought that was possible but google was NOT my friend... I like it

**Review by Allan-N — APPROVED** [review]

**Comment by mkmer** [comment]
May as well fix GPIO and add a message for invalid ones while we are tweaking this...

**Review by Allan-N — APPROVED** [review]
