### PR TITLE
app_rpt.c: add mutex_lock when setting audiohooks

### LINKED ISSUE #789: audiohook.c: FRACK!, Failed assertion bad magic number 0x0 for object 0x7fff04007128
While looking through logs to attempt to debug #763 I've discovered a periodic error with no surrounding context:

```
[2025-09-21 22:22:57.791] ERROR[1015827] audiohook.c: FRACK!, Failed assertion bad magic number 0x0 for object 0x7fff04007128 (0)
[2025-09-21 22:22:57.927] ERROR[1015827] : Got 7 backtrace records
# 0: [0x55563ba13988] asterisk :0 __ao2_lock()
# 1: [0x55563ba1ca78] asterisk :0 ast_audiohook_attach()
# 2: [0x55563ba1f6e8] asterisk :0 ast_audiohook_volume_set_float()
# 3: app_rpt.so <unknown>()
# 4: [0x55563bb92aa4] asterisk :0 ast_threadstorage_get()
# 5: [0x7fff2b4d2030] libc.so.6 pthread_create.c:442 start_thread()
# 6: [0x7fff2b53bf5c] libc.so.6 clone.S:82 thread_start()

[2025-09-21 22:22:57.927] ERROR[1015827] audiohook.c: FRACK!, Failed assertion bad magic number 0x0 for object 0x7fff04007128 (0)
[2025-09-21 22:22:58.029] ERROR[1015827] : Got 7 backtrace records
# 0: [0x55563ba13b8c] asterisk :0 __ao2_unlock()
# 1: [0x55563ba1cdc0] asterisk :0 ast_audiohook_attach()
# 2: [0x55563ba1f6e8] asterisk :0 ast_audiohook_volume_set_float()
# 3: app_rpt.so <unknown>()
# 4: [0x55563bb92aa4] asterisk :0 ast_threadstorage_get()
# 5: [0x7fff2b4d2030] libc.so.6 pthread_create.c:442 start_thread()
# 6: [0x7fff2b53bf5c] libc.so.6 clone.S:82 thread_start()
```

### PR DESCRIPTION
**Pull request by mkmer**
I have been watching this one for a bit. Looks like the telemetry thread can pull the rug out from the audio adjustment mid evaluation.  Since we expect `myrpt->active_telem` to remain "the same" non NULL value for the if statement, there should be a lock to prevent the race.
https://github.com/AllStarLink/app_rpt/blob/992a245bb05a3a9b06372dcc401ed658115e07e9/apps/app_rpt.c#L5297-L5314
Closes #789

### CODE REVIEW

File: apps/app_rpt.c [hunk 1]
```diff
@@ -5294,6 +5294,7 @@ static void *rpt(void *this)
 			}
 		}
 		/* If we have a new active telemetry message and a channel */
+		rpt_mutex_lock(&myrpt->lock);
```
Comment (Allan-N) [inline apps/app_rpt.c:5297]: Would grabbing a local copy of `myrpt->active_telem` avoid the need to grab the lock?

Comment (mkmer) [reply apps/app_rpt.c:5297]: I don't think so, when we clear out `myrpt->active_telem` we also hangup the channel, so I'm fairly sure we would still have a bad reference to the channel (in the structure).  I have only seen a few of these on our repeater, and have not seen any since adding the lock.

**Comment by mkmer** [comment]
Noting we removed this PR via PR #802 -> Turns out we were already locked.  
The actual problem is hanging up the channel while we still have a reference. PR #801 will prevent freeing the pointer until the telemetry thread has had the opportunity to clear the pointer.
