### PR TITLE
app_rpt: Update duplex mode 3 to pass audio to audioarchive.

### LINKED ISSUE #600: archivedir recording (mostly) silence to WAV file when duplex=3
**Describe the bug**
I am using the “archivedir” function to record repeater audio.  I have a single repeater with an RTCM attached to the ASL3 computer.  Audio is recorded to a WAV file (date_and_time_stamp.WAV as filename) each time someone keys up until they unkey (one file per key-up), as expected. 
 The files contain audio when duplex=2 in rpt.conf.  However, when duplex=3 in rpt.conf the files contain no received audio, but they do contain the courtesy tone and ID in CW (if present) at the end of the recording.  WAV files are of the appropriate size to contain audio and `ffprobe -v error -show_format 20250331003700.WAV` reports a file of 8-second duration.

**To Reproduce**
1) Add archivedir=/var/spool/asterisk/monitor to your node stanza in rpt.conf.
2) Key up your repeater and speak.
3) Play back the WAV file created in the /var/spool/asterisk/monitor/##### directory (where ##### is your actual node number)

**Expected behavior**
I expect to have a WAV (*.wav) file recorded that  has spoken audio from the person who keyed up the repeater and spoke.

**Software versions (listed in asl-menu, option 4)**
```
OS            : Debian GNU/Linux 12 (bookworm)
OS Kernel     : 6.1.0-32-amd64
Asterisk      : 22.2.0+asl3-3.3.0-6.deb12
ASL [app_rpt] : 3.3.0
Installed ASL packages :
Package                         Version
==============================  ==============================
allmon3                         1.4.2-1.deb12
asl3                            3.7.1-1.deb
asl3-asterisk                   2:22.2.0+asl3-3.3.0-6.deb12
asl3-asterisk-config            2:22.2.0+asl3-3.3.0-6.deb12
asl3-asterisk-modules           2:22.2.0+asl3-3.3.0-6.deb12
asl3-menu                       1.12-1.deb12
dahdi                           1:3.1.0-2
dahdi-dkms                      1:3.4.0-6+asl
dahdi-linux                     1:3.4.0-6+asl
```

**Have you run a software update and rebooted?**
Yes.

**What is the platform - e.g. Raspberry Pi 4, Raspberry Pi 5, Virtual Machine, Desktop, etc.**
Desktop - Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz

### PR DESCRIPTION
**Pull request by mkmer**
Mode 3 is intended to be a full duplex with local audio muted.  This WAS accomplished via conference settings but that prevented the local audio from reaching the monstream channel. Converting the conference settings to match modes 2 and 4 (full duplex) and simply muting the frames headed to the txchannel allows for monstream to catch the audio and prevent the audio from feeding back on the local speaker. Resolves issue archivedir recording (mostly) silence to WAV file when duplex=3 

Resolves #600

### CODE REVIEW

File: apps/app_rpt.c [hunk 1]
```diff
@@ -4024,6 +4024,9 @@ static inline int dahditxchannel_read(struct rpt *myrpt, char *restrict myfirst)
 			while ((f1 = AST_LIST_REMOVE_HEAD(&myrpt->txq, frame_list)))
 				ast_frfree(f1);
 		}
+		if (myrpt->p.duplex == 3 && myrpt->keyed) {
```
Comment (Allan-N) [inline apps/app_rpt.c:4027]: Should this "if" go inside the just above "else{}" (where duplex >= 2) ?

Comment (mkmer) [reply apps/app_rpt.c:4027]: Don't think so... Maybe should have used else if.

Comment (Allan-N) [reply apps/app_rpt.c:4027]: Except you empty out myrpt->txq in the else{}.

Comment (mkmer) [reply apps/app_rpt.c:4027]: Yah - I think this is as "good as it gets".  
Just muting frames in mode 3 if we are transmitting locally - same as before changing the conference, but now the monitor channel can catch the audio.

**Review by Allan-N — APPROVED** [review]

**Review by InterLinked1 — COMMENTED** [review]
monstream, not monostream?
