### PR TITLE
app_rpt: do_link_post snprintf using wrong size

### LINKED ISSUE #589: statpost truncated node string
Statpost is presenting a node string with "T " and no node value.

### PR DESCRIPTION
**Pull request by mkmer**
Updates to snprintf used the sizeof() on a malloc'd string resulting in truncated messages. 
Resolves #589

### CODE REVIEW

**Review by Allan-N — APPROVED** [review]

File: apps/app_rpt.c [hunk 1]
```diff
@@ -3284,21 +3284,22 @@ static inline void periodic_process_links(struct rpt *myrpt, const int elap)
...
 	for (l = myrpt->links.next; l != &myrpt->links; l = l->next) {
 		/* if is not a real link, ignore it */
 		if (l->name[0] == '0') {
 			continue;
 		}
-		nstr += strlen(l->name) + 1;
+		str_size += strlen(l->name) + 1;
 	}
-	str = ast_malloc(nstr + 256);
+	str_size += 256;
```
Comment (InterLinked1) [inline apps/app_rpt.c:3301]: I know this was here before, but what's the significance of 256?

File: apps/app_rpt.c [hunk 2]
```diff
@@ -3318,14 +3319,14 @@ static inline int do_link_post(struct rpt *myrpt)
 			lst = 'C';
 		if (nstr)
 			strcat(str, ",");
-		snprintf(str + strlen(str), sizeof(str) - strlen(str), "%c%s", lst, l->name);
+		snprintf(str + strlen(str), str_size - strlen(str), "%c%s", lst, l->name);
 		nstr = 1;
 	}
-	snprintf(str + strlen(str), sizeof(str) - strlen(str), "&apprptvers=%d.%d.%d", VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH);
+	snprintf(str + strlen(str), str_size - strlen(str), "&apprptvers=%d.%d.%d", VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH);
```
Comment (InterLinked1) [inline apps/app_rpt.c:3325]: Why do we even have multiple snprintf calls to build the URL? A single one would be much simpler and more efficient. No need to keep manipulating buffer sizes, etc.

File: apps/app_rpt.c (hunk 1 above)
Comment (mkmer) [reply apps/app_rpt.c:3301]: No Idea, just went with it. I probably should go with ast_str here and let it float.

**Review by Allan-N — APPROVED** [review]

**Review by InterLinked1 — APPROVED** [review]
