### PR TITLE
rpt_gps: failover to general_def_position if either coordinate is missing

### LINKED ISSUE #1015: rpt_gps.c: Research Rabbit comment around single NULL
_⚠️ Potential issue_ | _🔴 Critical_

**Guard the section-default path when either coordinate is missing.**

Lines 1130-1135 and Lines 1277-1282 only fall back to `general_def_position` when *both* coordinates are absent. If a section provides just one side, these branches still call `strtof(NULL, NULL)`, which is undefined behavior and can crash the sender thread. The APRStt branch also skips valid `ttlat`/`ttlon`-only configs because it checks `deflat`/`deflon` instead of the resolved coordinate pair.

<details>
<summary>🛠️ Suggested fix</summary>

```diff
-	if (!strcmp(ctg, "general") || (!deflat && !deflon)) {
+	if (!strcmp(ctg, "general") || !deflat || !deflon) {
 		this_def_position = general_def_position;
 	} else {
```

```c
const char *resolved_lat = ttlat ? ttlat : deflat;
const char *resolved_lon = ttlon ? ttlon : deflon;

if (!strcmp(ctg, "general") || !resolved_lat || !resolved_lon) {
	this_def_position = general_def_position;
} else {
	this_def_position.is_valid = 1;
	lat_decimal_to_DMS(strtof(resolved_lat, NULL), this_def_position.latitude, sizeof(this_def_position.latitude));
	lon_decimal_to_DMS(strtof(resolved_lon, NULL), this_def_position.longitude, sizeof(this_def_position.longitude));
	...
}
```
</details>

Also applies to: 1277-1282

<details>
<summary>🤖 Prompt for AI Agents</summary>

```
Verify each finding against the current code and only fix it if needed.

In `@apps/app_gps.c` around lines 1130 - 1135, The branch currently falls back to
general_def_position only when both deflat and deflon are NULL, causing
strtof(NULL,...) if one coordinate is missing; update the logic to first compute
resolved_lat and resolved_lon (use ttlat if present else deflat, and ttlon if
present else deflon) and then check if either resolved_lat or resolved_lon is
NULL (or ctg == "general") to decide to use general_def_position; otherwise mark
this_def_position.is_valid and call lat_decimal_to_DMS and lon_decimal_to_DMS
with the resolved strings; apply the same fix to the APRStt-related block that
currently inspects deflat/deflon instead of the resolved pair.
```

</details>

_Originally posted by @coderabbitai[bot] in https://github.com/AllStarLink/app_rpt/pull/1014#discussion_r3060077747_

### PR DESCRIPTION
**Pull request by okcrum**
Current behavior only fails over if both coordinates are missing.

Fixes: #1015

## Bug Fixes
* Improved GPS position fallback behavior to use default coordinates when coordinate data is incomplete or unavailable, rather than only when data is entirely absent.

### CODE REVIEW

**Comment by okcrum** [comment]
@coderabbitai review

File: apps/app_gps.c [hunk 1]
```diff
@@ -1273,8 +1273,32 @@ static void *aprstt_sender_thread(void *data)
...
+			float eleva, elevd;
+			eleva = strtof(defelev, NULL);
+			elevd = (eleva - floor(eleva)) * 10 + 0.5;
+			snprintf(this_def_position.elevation, sizeof(this_def_position.elevation), "%03d.%1d", (int) eleva, (int) elevd);
+		} else {
+			strcpy(this_def_position.elevation, "000.0");
+		}
+	}
+
+	if (!strcmp(ctg, "general") || !deflat || !deflon) {
```
Comment (Allan-N) [inline apps/app_gps.c]: Something's odd with this change.  You added the lines above (l.1281 ... 1299) but then we still have this block (l.1301 ... 1316)

Comment (okcrum) [reply apps/app_gps.c]: I think that was a miss on the removal of the old block, which I had saved. Doh!

It's removed now.

**Review by Allan-N — APPROVED** [review]
