### PR TITLE
app_rpt: rpt_vars[]->ready never set true for remote.  Issue created by PR#532

### LINKED ISSUE #681: ASL3 remote base not working
Trying to make the built in RB work. But it doesn't. Included in node rpt.conf I added:

remote = ft100
ioport = /dev/ttyACM0
iospeed = 4800

I know these configs are correct as I used them in ASL2 remote and also the port and speed work fine on the same PC with hamlib. 

If I change the nodes node line to delete the "Y" at the end of the line and then comment out the remote specific lines notes above this node 2428 can be connected to from another. But when remote base is enabled you cannot connect to the remote node. 

It was suggested to me to open a ticket because one person on the developer list is already running a remote. Maybe she or he can give me pointers

GeorgeC W2DB

PS just to make more certain I;m doing things correctly I swapped drives to a ASL2 installation. Remote worked fine.

### PR DESCRIPTION
**Pull request by mkmer**
Resolves #681

### CODE REVIEW

File: apps/app_rpt.c [hunk 1]
```diff
@@ -5672,7 +5672,8 @@ static void *rpt_master(void *ignore)
 
 		/* if is a remote, dont start one for it */
```
Comment (Allan-N) [inline apps/app_rpt.c:5673]: This comment, especially here, is confusing.  Does the comment really belong "in" (or at least inline with) the `if () { }` block?  and would the `else { }` inline comment be better "in" the `else` block?

Also, what are we not starting?  and how does not starting whatever sync up with marking it as "ready"?

**Review by Allan-N — APPROVED** [review]

File: apps/app_rpt.c (hunk 1 above)
Comment (mkmer) [reply apps/app_rpt.c:5673]: "start em all..." that's what were not starting :)  

If we are remote, the repeater threads are NOT started:
https://github.com/AllStarLink/app_rpt/blob/34b33105962433d7403b88d6a3f13700e6efd03c/apps/app_rpt.c#L5707

What should we put in the comments to help clear this up?
