### PR TITLE
app_rpt: Write channel text messages to `rpt_qwrite()`

### LINKED ISSUE #958: `rpt sendtext` fails with blocking
Attempting to send a text with `rpt sendtext` 

[2026-03-01 13:41:13.278] DEBUG[701555]: channel.c:4721 ast_sendtext_data: Thread LWP 701555 is blocking 'IAX2/149.154.11.231:53627-12624', already blocked by thread LWP 703364 in procedure ast_waitfor_nandfds

### PR DESCRIPTION
**Pull request by mkmer**
`ast_sendtext()` can not be called while other threads are waiting on the channel.
Fixes #958 

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved text message delivery by switching from immediate send to queue-based delivery when a channel is active. This reduces race conditions and improves reliability and ordering of outbound messages while preserving prior behavior when no active channel is present.

### CODE REVIEW

File: apps/app_rpt/rpt_functions.c [hunk 1]
```diff
@@ -66,12 +66,17 @@ int rpt_sendtext_cb(void *obj, void *arg, int flags)
 {
 	struct rpt_link *link = obj;
 	char *str = arg;
+	struct ast_frame wf;
```
Comment (Allan-N) [inline apps/app_rpt/rpt_functions.c]: See below
