### PR TITLE
app_rpt:  Channel initialization for PTT

### LINKED ISSUE #421: PTT stuck on at boot (invertptt = yes)
I am in the process of upgrading my shack away from raspberry pi's. Consolidating all the individual rpi's functions onto a 8 core Intel(R) Atom(TM) CPU C2758 @ 2.40GHz CPU, 32GB ram, 512G SSD machine. The bare metal has Proxmox 8.2.7 on it. All of the various other functions (Allstar, APRS, APRSC, WEEWX, NOAAv2, OpenWebRX, ADS-B, and likely others I have forgotten at this moment) I have been able to get to work as a CT rather then as a VM except Allstar. So Allstar is the only VM and has a dedicated CM108 passed through to it.  Yes I agree, it is complete overkill....

**Describe the bug**
I am experiencing an issue with the PTT being stuck keyed upon first boot or whenever asterisk is restarted. To make it "behave" I went into Interface Tune CLI, and entered F to make the transmitter key up a few times with a test tone. (obviously the PTT is already keyed) Upon doing so the 3 tones can be heard, and once done the PTT remains off. From that point forward the PTT operates as per normal until the next reboot or restart of asterisk.

For a possible reference, a similar sounding but not exactly the same issue from the past: https://github.com/AllStarLink/ASL3/issues/76 

**To Reproduce**
Steps to reproduce the behaviour:
1. Warm or Cold boot the system (PTT is unkeyed at this point throughout BIOS and into the early stages of loading Debian12)
2. As the system boot nears the console prompt the PTT becomes keyed and remains keyed indefinitely.  The longest I have waited was 10min (radio was on ultra low power into a dummy load)
3. At this point if I enter the ASL-Menu and drill into the Interface Tuning CLI and initiate a F (Toggle PTT and Tone output several times) the radio will transmit 3x tones. The 1st tone is heard, PTT drops, PTT keys + 2nd tone, PTT drops, PTT keys + 3rd tone, PTT drops. At the conclusion of the 3rd tone the PTT remains off. 
4. PTT will now key up correctly from here forward because of local rf, internet traffic, telemetry, etc until the next reboot or restart of asterisk.

**Expected behaviour**
- Expected behaviour is that upon boot the PTT would remain in an unkeyed state until an active TX event initiates. 
- Expected behaviour is that upon restarting asterisk the PTT would remain in an unkeyed state until an active TX event initiates.

Software versions (listed in asl-menu, option 4)
OS            : Debian GNU/Linux 12 (bookworm)
OS Kernel     : 6.1.0-26-amd64
Asterisk      : 20.9.3+asl3-3.0.6-1.deb12
ASL [app_rpt] : 3.0.6
Installed ASL packages :
Package                         Version
 ==============================  
allmon3                         1.4.1-1.deb12
asl3                                3.5.0-1.deb
asl3-asterisk                   2:20.9.3+asl3-3.0.6-1.deb12
asl3-asterisk-config         2:20.9.3+asl3-3.0.6-1.deb12
asl3-asterisk-modules     2:20.9.3+asl3-3.0.6-1.deb12
asl3-menu                      1.9-1.deb12
dahdi                              1:3.1.0-2
dahdi-dkms                    1:3.4.0-4+asl
dahdi-linux                     1:3.4.0-4+asl

**Have you run a software update and rebooted?**
 - YES

**Platform**
  - A fresh Debian 12 Virtual Machine (non UEFI) running under a fresh Proxmox v8.2.7 
    (followed these instructions: https://allstarlink.github.io/user-guide/install/ )
  - CM108 usb is attached to the VM via hardware passthru
  - Radio Interface is a CM108 as a SimpleUSB device, Duplex 2.

**Additional context**
Using a CM108 to interface to the radios CDM750's. (In the past this adapter has worked flawlessly for years on these same radios while on a rpi 3b+ and the older allstar version) 
I am aware there are a few variants of CM108's out there but I am not sure how to identify this any more accurately as the pcb has been encapsulated in black expoxy and I can not read the writing on the chip.  

lsusb shows it as: 0d8c:000c C-Media Electronics, Inc. Audio Adapter

nano /sys/kernel/debug/usb/devices
T:  Bus=02 Lev=01 Prnt=01 Port=00 Cnt=01 Dev#=  2 Spd=12   MxCh= 0
D:  Ver= 1.10 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=0d8c ProdID=000c Rev= 1.00
S:  Product=C-Media USB Headphone Set
C:* #Ifs= 4 Cfg#= 1 Atr=80 MxPwr=100mA
I:* If#= 0 Alt= 0 #EPs= 0 Cls=01(audio) Sub=01 Prot=00 Driver=snd-usb-audio
I:  If#= 1 Alt= 0 #EPs= 0 Cls=01(audio) Sub=02 Prot=00 Driver=snd-usb-audio
I:* If#= 1 Alt= 1 #EPs= 1 Cls=01(audio) Sub=02 Prot=00 Driver=snd-usb-audio
E:  Ad=01(O) Atr=09(Isoc) MxPS= 200 Ivl=1ms
I:  If#= 2 Alt= 0 #EPs= 0 Cls=01(audio) Sub=02 Prot=00 Driver=snd-usb-audio
I:* If#= 2 Alt= 1 #EPs= 1 Cls=01(audio) Sub=02 Prot=00 Driver=snd-usb-audio
E:  Ad=82(I) Atr=05(Isoc) MxPS= 100 Ivl=1ms
I:* If#= 3 Alt= 0 #EPs= 1 Cls=03(HID  ) Sub=00 Prot=00 Driver=usbfs
E:  Ad=83(I) Atr=03(Int.) MxPS=   4 Ivl=32ms

/var/log/asterisk/messages.log from the last boot up
`
[2024-11-04 13:48:55.291] Asterisk 20.9.3+asl3-3.0.6-1.deb12 built by builder @ allstarlink.org on a x86_64 running Linux on 2024-10-05 13:19:13 UTC
[2024-11-04 13:48:55.348] NOTICE[481] loader.c: 71 modules will be loaded.
[2024-11-04 13:48:55.592] NOTICE[481] cdr.c: CDR simple logging enabled.
[2024-11-04 13:48:55.596] NOTICE[481] dnsmgr.c: Managed DNS entries will be refreshed every 300 seconds.
[2024-11-04 13:48:55.624] NOTICE[481] indications.c: Default country for indication tones: us
[2024-11-04 13:48:55.624] NOTICE[481] indications.c: Setting default indication country to 'us'
[2024-11-04 13:48:55.746] NOTICE[481] res_smdi.c: No SMDI interfaces are available to listen on, not starting SMDI listener.
[2024-11-04 13:48:55.761] WARNING[481] chan_dahdi.c: Only FXO signalled channels may belong to a call group
[2024-11-04 13:48:55.761] WARNING[481] chan_dahdi.c: Only FXO signalled channels may belong to a pickup group
[2024-11-04 13:48:55.761] NOTICE[481] chan_dahdi.c: Ignoring any changes to 'userbase' (on reload) at line 23.
[2024-11-04 13:48:55.761] NOTICE[481] chan_dahdi.c: Ignoring any changes to 'vmsecret' (on reload) at line 31.
[2024-11-04 13:48:55.761] NOTICE[481] chan_dahdi.c: Ignoring any changes to 'hassip' (on reload) at line 35.
[2024-11-04 13:48:55.761] NOTICE[481] chan_dahdi.c: Ignoring any changes to 'hasiax' (on reload) at line 39.
[2024-11-04 13:48:55.761] NOTICE[481] chan_dahdi.c: Ignoring any changes to 'hasmanager' (on reload) at line 47.
[2024-11-04 13:48:55.761] WARNING[481] chan_dahdi.c: Only FXO signalled channels may belong to a call group
[2024-11-04 13:48:55.761] WARNING[481] chan_dahdi.c: Only FXO signalled channels may belong to a pickup group
[2024-11-04 13:48:56.096] WARNING[481] loader.c: Module 'res_adsi' has been loaded but may be removed in a future release.
[2024-11-04 13:48:56.323] NOTICE[644] app_rpt.c: Normal Repeater Init 53011
[2024-11-04 13:48:56.329] NOTICE[652] chan_simpleusb.c: Channel 53011: Set option TONE VERIFY, mode: OFF(0).
[2024-11-04 13:48:56.352] ERROR[653] chan_simpleusb.c: Channel 53011: Device string 2-1:1.0 was not found.
[2024-11-04 13:53:04.644] Asterisk 20.9.3+asl3-3.0.6-1.deb12 built by builder @ allstarlink.org on a x86_64 running Linux on 2024-10-05 13:19:13 UTC
[2024-11-04 13:53:04.694] NOTICE[491] loader.c: 71 modules will be loaded.
[2024-11-04 13:53:04.939] NOTICE[491] cdr.c: CDR simple logging enabled.
[2024-11-04 13:53:04.943] NOTICE[491] dnsmgr.c: Managed DNS entries will be refreshed every 300 seconds.
[2024-11-04 13:53:04.971] NOTICE[491] indications.c: Default country for indication tones: us
[2024-11-04 13:53:04.971] NOTICE[491] indications.c: Setting default indication country to 'us'
[2024-11-04 13:53:05.091] NOTICE[491] res_smdi.c: No SMDI interfaces are available to listen on, not starting SMDI listener.
[2024-11-04 13:53:05.103] WARNING[491] chan_dahdi.c: Only FXO signalled channels may belong to a call group
[2024-11-04 13:53:05.103] WARNING[491] chan_dahdi.c: Only FXO signalled channels may belong to a pickup group
[2024-11-04 13:53:05.103] NOTICE[491] chan_dahdi.c: Ignoring any changes to 'userbase' (on reload) at line 23.
[2024-11-04 13:53:05.103] NOTICE[491] chan_dahdi.c: Ignoring any changes to 'vmsecret' (on reload) at line 31.
[2024-11-04 13:53:05.103] NOTICE[491] chan_dahdi.c: Ignoring any changes to 'hassip' (on reload) at line 35.
[2024-11-04 13:53:05.103] NOTICE[491] chan_dahdi.c: Ignoring any changes to 'hasiax' (on reload) at line 39.
[2024-11-04 13:53:05.103] NOTICE[491] chan_dahdi.c: Ignoring any changes to 'hasmanager' (on reload) at line 47.
[2024-11-04 13:53:05.103] WARNING[491] chan_dahdi.c: Only FXO signalled channels may belong to a call group
[2024-11-04 13:53:05.103] WARNING[491] chan_dahdi.c: Only FXO signalled channels may belong to a pickup group
[2024-11-04 13:53:05.336] WARNING[491] loader.c: Module 'res_adsi' has been loaded but may be removed in a future release.
[2024-11-04 13:53:05.403] NOTICE[615] app_rpt.c: Normal Repeater Init 53011
[2024-11-04 13:53:05.408] NOTICE[622] chan_simpleusb.c: Channel 53011: Set option TONE VERIFY, mode: OFF(0).
[2024-11-04 14:04:26.475] Asterisk 20.9.3+asl3-3.0.6-1.deb12 built by builder @ allstarlink.org on a x86_64 running Linux on 2024-10-05 13:19:13 UTC
[2024-11-04 14:04:26.531] NOTICE[491] loader.c: 71 modules will be loaded.
[2024-11-04 14:04:26.770] NOTICE[491] cdr.c: CDR simple logging enabled.
[2024-11-04 14:04:26.773] NOTICE[491] dnsmgr.c: Managed DNS entries will be refreshed every 300 seconds.
[2024-11-04 14:04:26.800] NOTICE[491] indications.c: Default country for indication tones: us
[2024-11-04 14:04:26.800] NOTICE[491] indications.c: Setting default indication country to 'us'
[2024-11-04 14:04:26.918] NOTICE[491] res_smdi.c: No SMDI interfaces are available to listen on, not starting SMDI listener.
[2024-11-04 14:04:26.933] WARNING[491] chan_dahdi.c: Only FXO signalled channels may belong to a call group
[2024-11-04 14:04:26.933] WARNING[491] chan_dahdi.c: Only FXO signalled channels may belong to a pickup group
[2024-11-04 14:04:26.933] NOTICE[491] chan_dahdi.c: Ignoring any changes to 'userbase' (on reload) at line 23.
[2024-11-04 14:04:26.933] NOTICE[491] chan_dahdi.c: Ignoring any changes to 'vmsecret' (on reload) at line 31.
[2024-11-04 14:04:26.933] NOTICE[491] chan_dahdi.c: Ignoring any changes to 'hassip' (on reload) at line 35.
[2024-11-04 14:04:26.933] NOTICE[491] chan_dahdi.c: Ignoring any changes to 'hasiax' (on reload) at line 39.
[2024-11-04 14:04:26.933] NOTICE[491] chan_dahdi.c: Ignoring any changes to 'hasmanager' (on reload) at line 47.
[2024-11-04 14:04:26.933] WARNING[491] chan_dahdi.c: Only FXO signalled channels may belong to a call group
[2024-11-04 14:04:26.933] WARNING[491] chan_dahdi.c: Only FXO signalled channels may belong to a pickup group
[2024-11-04 14:04:27.498] WARNING[491] loader.c: Module 'res_adsi' has been loaded but may be removed in a future release.
[2024-11-04 14:04:27.736] NOTICE[615] app_rpt.c: Normal Repeater Init 53011
[2024-11-04 14:04:27.741] NOTICE[624] chan_simpleusb.c: Channel 53011: Set option TONE VERIFY, mode: OFF(0).
[2024-11-04 14:09:27.284] NOTICE[596] dnsmgr.c: dnssrv: host 'register.allstarlink.org' changed from 34.105.111.212:443 to 162.248.92.131:443
`

simpleusb.conf
`
;!
;! Automatically generated configuration file
;! Filename: simpleusb.conf (/etc/asterisk/simpleusb.conf)
;! Generator: chan_simpleusb
;! Creation Date: Mon Nov  4 14:27:29 2024
;!
;***************************************************
;********   Template-tized simpleusb.conf   ********
;***************************************************
; Note to editors: set tabs to 4 space characters. No wrap to keep comments neat.
; vim: tabstop=4
;
; SimpleUSB channel driver Configuration File
;
;;;;;                 New to ASL3                 ;;;;;
;;;;; The SimpleUSB "tune" settings have moved to ;;;;;
;;;;; this file. The simpleusb_tune_usb_1999.conf ;;;;;
;;;;; file is no longer used.                     ;;;;;

; If you are going to use this channel driver, you MUST enable it in modules.conf
; change:
; noload => chan_simpleusb.so       ; CM1xx USB Cards with Radio Interface Channel Driver (No DSP)
; noload => res_usbradio.so         ; Required for both simpleusb and usbradio
; to:
; load => chan_simpleusb.so         ; CM1xx USB Cards with Radio Interface Channel Driver (No DSP)
; load => res_usbradio.so           ; Required for both simpleusb and usbradio

[general]
;------------------------------ JITTER BUFFER CONFIGURATION --------------------------
; jbenable = yes              ; Enables the use of a jitterbuffer on the receiving side of an
; simpleusb channel. Defaults to "no". An enabled jitterbuffer will
; be used only if the sending side can create and the receiving
; side can not accept jitter. The simpleusb channel can't accept jitter,
; thus an enabled jitterbuffer on the receive simpleusb side will always
; be used if the sending side can create jitter.

; jbmaxsize = 200             ; Max length of the jitterbuffer in milliseconds.

; jbresyncthreshold = 1000    ; Jump in the frame timestamps over which the jitterbuffer is
; resynchronized. Useful to improve the quality of the voice, with
; big jumps in/broken timestamps, usualy sent from exotic devices
; and programs. Defaults to 1000.

; jbimpl = fixed              ; Jitterbuffer implementation, used on the receiving side of an simpleusb
; channel. Two implementations are currenlty available - "fixed"
; (with size always equals to jbmax-size) and "adaptive" (with
; variable size, actually the new jb of IAX2). Defaults to fixed.

; jblog = no                  ; Enables jitterbuffer frame logging. Defaults to "no".
;-----------------------------------------------------------------------------------

[node-main](!)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;; Template for all your SimpleUSB nodes ;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

eeprom = 0  ; EEPROM installed: 0,1
; 0 = no (default)
; 1 = yes

hdwtype = 0  ; Leave this set to 0 for USB sound fobs designed for app_rpt
; or modified cmxxx sound fobs.
; 1 is for Dingotel/Sph interfaces.
; 2 is for NHC interfaces.
; 3 is for a custom interface.

; Receiver parameters
rxboost = no  ; no = 20db attenuator inserted, yes = 20db attenuator removed
; Set to yes for additonal gain if using a low-level receiver output
; CM119B devices are hard coded to rxboost 20dB attenuator removed

carrierfrom = usbinvert  ; no,usb,usbinvert
; no - no carrier detection at all
; usb - from the COR line on the USB sound fob (Active high)
; usbinvert - from the inverted COR line on the USB sound fob (Active low)
; pp - from parallel port (Active high)
; ppinvert - from the inverted parallel port (Active low)

ctcssfrom = usbinvert  ; no,usb,usbinvert
; no - CTCSS decoding, system will be carrier squelch
; usb - CTCSS decoding using input from USB sound fob (Active high)
; usbinvert - from the inverted CTCSS line on the USB sound fob (Active low)
; pp - from parallel port (Active high)
; ppinvert - from the inverted parallel port (Active low)

deemphasis = no  ; enable de-emphasis (input from discriminator)

plfilter = yes  ; enable PL filter

rxondelay = 0  ; Number of 20mSec intervals following the release of PTT.
; Uncomment and/or adjust for simplex nodes to eliminate "Ping Ponging"
; or "Relay Racing". A positive value here will instruct the usbradio
; driver to ignore the COR line for a specified number of 20mSec
; intervals following the release of PTT. Use this ONLY on simplex
; nodes, and leave commented out for repeaters or other full duplex nodes.

txoffdelay = 0  ; Ignore the reciever for a specified number of 20 millisecond
; intervals after the transmitter unkeys.
; This is useful when setting up a half-duplex link with an existing
; repeater, where you need to ignore the repeater's hangtime.

; Transmitter parameters
txmixa = voice  ; Left channel output (A): no,voice
; no - Do not output anything
; voice - output voice only

txmixb = no  ; Right channel output (B): no,voice
; no - Do not output anything
; voice - output voice only

invertptt = no  ; Invert PTT: no,yes
; no  - ground to transmit
; yes - open to transmit

preemphasis = no  ; Perform standard 6db/octave pre-emphasis

; pager = no                        ; no,a,b (e.g. pager = b means "put the normal repeat audio on channel A, and the pager audio on channel B")

; duplex3 = 0                       ; duplex 3 gain setting (0 to disable)

clipledgpio = 1  ; Enable ADC Clip Detect feature to use a GPIO output (0 to disable).
; Supports URI Clip LED by setting a GPIO (if available) high for 500mS
; when clipping detected. Value = GPIO# to use (GPIO1 recommended)

;;; End of node-main template

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;; Configure your nodes here ;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; Note: there is no need to duplicate entire settings. Only
;       place settings that are different than the template.
;
; Note: the device string is automatically found when the
;       USB setting "devstr=" is empty.
;
; Note: the interface "tune" settings will be added to the
;       per-node settings (below).

[53011](node-main)
preemphasis = yes
ctcssfrom = no

plfilter = no
invertptt = yes

;;;;; ASL3 Tune settings ;;;;;
devstr =
rxmixerset = 300
txmixaset = 700
txmixbset = 700
`

If there is any other information I have forgotten to attach please let me know. 

Thank you for your assistance.

### PR DESCRIPTION
**Pull request by KB4MDD**
app_rpt is not waiting long enough in rpt_setup_channels for chan_simpleusb to initialize the usb device before asserting PTT on/off.

This change adds a 250ms delay before asserting PTT on and another 50ms delay before asserting PTT off.

I believe the intention of the original code was to insure that the PTT was toggled immediately after the channel driver was created by app_rpt.

Testing by the effected users is needed. This may close #421 and #424.

### CODE REVIEW

File: apps/app_rpt.c [hunk 1]
```diff
@@ -2695,8 +2695,12 @@ static int rpt_setup_channels(struct rpt *myrpt, struct ast_format_cap *cap)
 		myrpt->txchannel = myrpt->rxchannel;
 		myrpt->dahditxchannel = IS_DAHDI_CHAN_NAME(myrpt->rxchanname) && !IS_PSEUDO_NAME(myrpt->rxchanname) ? myrpt->txchannel : NULL;
 	}
+	/* If the TX channel is not a pseudo channel, toggle the PTT line */
 	if (!IS_PSEUDO(myrpt->txchannel)) {
+		/* Wait for the driver to finish initialization */
+		usleep(250000);
```
Comment (InterLinked1) [inline apps/app_rpt.c:2701]: Do not use usleep when sleeping on a channel, use `ast_safe_sleep` instead.
Keep in mind the latter uses ms, not us like usleep.

File: apps/app_rpt.c [hunk 2]
```diff
@@ -2695,8 +2695,12 @@ static int rpt_setup_channels(struct rpt *myrpt, struct ast_format_cap *cap)
 		myrpt->txchannel = myrpt->rxchannel;
 		myrpt->dahditxchannel = IS_DAHDI_CHAN_NAME(myrpt->rxchanname) && !IS_PSEUDO_NAME(myrpt->rxchanname) ? myrpt->txchannel : NULL;
 	}
+	/* If the TX channel is not a pseudo channel, toggle the PTT line */
 	if (!IS_PSEUDO(myrpt->txchannel)) {
+		/* Wait for the driver to finish initialization */
```
Comment (InterLinked1) [inline apps/app_rpt.c:2700]: Why is 250 ms enough to finish initialization? Is there a more direct way to wait for initialization to finish? How do we know that has happened?

**Review by InterLinked1 — CHANGES_REQUESTED** [review]

**Comment by Allan-N** [comment]
FYI : I removed the delays that @KB4MDD added and added a log message inside kickptt() when called with the PTT pipe not yet established.  Here's the output :
```
[2024-11-21 13:30:52.289] ERROR[301772]: chan_simpleusb.c:655 kickptt: Channel 491301: Write skipped: no pttkick[]
[2024-11-21 13:30:52.289] ERROR[301772]: chan_simpleusb.c:655 kickptt: Channel 491301: Write skipped: no pttkick[]
```
This confirms @KB4MDD's analysis that app_rpt's PTT toggling was likely happening before the hiddriver() thread had a chance to initialize the GPIO pins (and PTT pipe).

With the SimpleUSB and USBRadio GPIO changes I added to correctly initialize the GPIO pins neither @KB4MDD or I think the toggling code is needed (and will be removed with the next commit).
