### PR TITLE
Audiohook FRACK resolution

### LINKED ISSUE #800: audiohook.c FRACK!
```
error.log.1:[2025-10-05 19:25:14.894] ERROR[1195919] audiohook.c: FRACK!, Failed assertion bad magic number 0x0 for object 0x7f69fc00b630 (0)
error.log.1:# 1: /usr/sbin/asterisk(ast_audiohook_attach+0x40) [0x5648972e46c0]
error.log.1:# 2: /usr/sbin/asterisk(ast_audiohook_volume_set_float+0x21b) [0x5648972e76cb]
error.log.1:[2025-10-05 19:25:14.895] ERROR[1195919] audiohook.c: FRACK!, Failed assertion bad magic number 0x0 for object 0x7f69fc00b630 (0)
error.log.1:# 1: /usr/sbin/asterisk(ast_audiohook_attach+0x3b8) [0x5648972e4a38]
error.log.1:# 2: /usr/sbin/asterisk(ast_audiohook_volume_set_float+0x21b) [0x5648972e76cb]
error.log.10.gz:[2025-08-06 17:27:09.009] ERROR[2638637] audiohook.c: FRACK!, Failed assertion bad magic number 0x0 for object 0x7fdeb80127a0 (0)
error.log.10.gz:# 1: /usr/sbin/asterisk(ast_audiohook_attach+0x3c) [0x5628b15ed7fc]
error.log.10.gz:# 2: /usr/sbin/asterisk(ast_audiohook_volume_set_float+0x21b) [0x5628b15f079b]
```

I suspect a race between the telemetry thread hanging up on a channel and the "keyup/unkey" code trying to set the gain.
ATM it appears to be more of a "warning" without adverse effect.

### PR DESCRIPTION
**Pull request by mkmer**
Adding a channel reference prevents hangup and pbx (which also finishes with hangup) from freeing the channel before `rpt_tele_thread()` has a chance to clear the active channel pointer.  Freeing "early" causes the audiohook calls to access a freed channel pointer resulting in FRACK! error.
Fixes #800

### CODE REVIEW

File: apps/app_rpt/rpt_telemetry.c [hunk 1]
```diff
@@ -2896,6 +2898,7 @@ void *rpt_tele_thread(void *this)
 	ast_free(mytele);
 	if (mychannel) {
 		ast_hangup(mychannel);
+		ast_channel_unref(mychannel);
```
Comment (InterLinked1) [inline apps/app_rpt/rpt_telemetry.c]: Why do we unref here a second time?

Comment (InterLinked1) [reply apps/app_rpt/rpt_telemetry.c]: Yeah, missed that when I was skimming the code

**Review by InterLinked1 — APPROVED** [review]
